services:
    Sidus\FilterBundle\Factory\FilterFactoryInterface:
        alias: Sidus\FilterBundle\Factory\FilterFactory

    Sidus\FilterBundle\Factory\FilterFactory:
        public: false

    Sidus\FilterBundle\Factory\QueryHandlerConfigurationFactoryInterface:
        alias: Sidus\FilterBundle\Factory\QueryHandlerConfigurationFactory

    Sidus\FilterBundle\Factory\QueryHandlerConfigurationFactory:
        public: false
        autowire: true
