services:
    Sidus\FilterBundle\Form\Type\DateRangeType:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    Sidus\FilterBundle\Form\Type\OrderButtonType:
        public: false
        tags:
            - { name: form.type }

    Sidus\FilterBundle\Form\Type\SortConfigType:
        public: false
        arguments:
            - Sidus\FilterBundle\DTO\SortConfig
        tags:
            - { name: form.type }

    Sidus\FilterBundle\Form\Type\ComboFilterType:
        public: false
        tags:
              - { name: form.type }
